/* Creamos algunos usuarios con sus roles */
INSERT INTO `accounts` (username, password, email, name, surnames, image, enabled) VALUES ('andres','$2a$10$O9wxmH/AeyZZzIS09Wp8YOEMvFnbRVJ8B4dmAMVSGloR62lj.yqXG','abb@gmail.com','Albert','Badia Atun','',1);
INSERT INTO `accounts` (username, password, email, name, surnames, image, enabled) VALUES ('admin','$2a$10$DOMDxjYyfZ/e7RcBfUpzqeaCs8pLgcizuiQWXPkU35nOhZlFcE9MS','jaumeparrot2@gmail.com','Jaume','Parrot Altisent','',1);

INSERT INTO `authorities` (account_id, authority) VALUES (1,'ROLE_USER');
INSERT INTO `authorities` (account_id, authority) VALUES (2,'ROLE_ADMIN');
INSERT INTO `authorities` (account_id, authority) VALUES (2,'ROLE_USER');

/* Populate tabla activities */
INSERT INTO activities (title, activity_date, start_time, end_time, description, place_activity, meeting_point, image_event, account_id)VALUES('Pica-pica', '2018-09-09', '15:30', '17:00', '¿Te gustaría tomar una cerveza y que el pica-pica fuese gratis? Pues solo tienes que venir este jueves 6 de septiembre a El Patrón de Barcelona y podrás picotear entre risas y conocer gente guapa.', 'El Patrón. Travessera de Gràcia, 44-46, 08021 Barcelona (entre Aribau y Muntaner)', 'Dentro de El Patrón a las 19:30h', 'image/d', 1);
INSERT INTO activities (title, activity_date, start_time, end_time, description, place_activity, meeting_point, image_event, account_id)VALUES('Tomar un café', '2018-09-09', '15:30', '17:00', '¿Te gustaría tomar una cerveza y que el pica-pica fuese gratis? Pues solo tienes que venir este jueves 6 de septiembre a El Patrón de Barcelona y podrás picotear entre risas y conocer gente guapa.rrrrrrrrrrrrrrrr', 'El Patrón. Travessera de Gràcia, 44-46, 08021 Barcelona (entre Aribau y Muntaner)', 'Dentro de El Patrón a las 19:30h', 'image/d', 1);
INSERT INTO activities (title, activity_date, start_time, end_time, description, place_activity, meeting_point, image_event, account_id)VALUES('Pachanga futbol', '2018-09-09', '15:30', '17:00', '¿Te gustaría tomar una cerveza y que el pica-pica fuese gratis? Pues solo tienes que venir este jueves 6 de septiembre a El Patrón de Barcelona y podrás picotear entre risas y conocer gente guapa.', 'El Patrón. Travessera de Gràcia, 44-46, 08021 Barcelona (entre Aribau y Muntaner)', 'Dentro de El Patrón a las 19:30h', 'image/d', 1);
INSERT INTO activities (title, activity_date, start_time, end_time, description, place_activity, meeting_point, image_event, account_id)VALUES('Picsa la nano', '2018-09-09', '15:30', '17:00', '¿Te gustaría tomar una cerveza y que el pica-pica fuese gratis? Pues solo tienes que venir este jueves 6 de septiembre a El Patrón de Barcelona y podrás picotear entre risas y conocer gente guapa.', 'El Patrón. Travessera de Gràcia, 44-46, 08021 Barcelona (entre Aribau y Muntaner)', 'Dentro de El Patrón a las 19:30h', 'image/d', 1);
INSERT INTO activities (title, activity_date, start_time, end_time, description, place_activity, meeting_point, image_event, account_id)VALUES('Ball de solo', '2018-09-09', '15:30', '17:00', '¿Te gustaría tomar una cerveza y que el pica-pica fuese gratis? Pues solo tienes que venir este jueves 6 de septiembre a El Patrón de Barcelona y podrás picotear entre risas y conocer gente guapa.', 'El Patrón. Travessera de Gràcia, 44-46, 08021 Barcelona (entre Aribau y Muntaner)', 'Dentro de El Patrón a las 19:30h', 'image/d', 1);
INSERT INTO activities (title, activity_date, start_time, end_time, description, place_activity, meeting_point, image_event, account_id)VALUES('Biciclenjo', '2018-09-09', '15:30', '17:00', '¿Te gustaría tomar una cerveza y que el pica-pica fuese gratis? Pues solo tienes que venir este jueves 6 de septiembre a El Patrón de Barcelona y podrás picotear entre risas y conocer gente guapa.', 'El Patrón. Travessera de Gràcia, 44-46, 08021 Barcelona (entre Aribau y Muntaner)', 'Dentro de El Patrón a las 19:30h', 'image/d', 1);
INSERT INTO activities (title, activity_date, start_time, end_time, description, place_activity, meeting_point, image_event, account_id)VALUES('Pica-pica', '2018-09-09', '15:30', '17:00', '¿Te gustaría tomar una cerveza y que el pica-pica fuese gratis? Pues solo tienes que venir este jueves 6 de septiembre a El Patrón de Barcelona y podrás picotear entre risas y conocer gente guapa.', 'El Patrón. Travessera de Gràcia, 44-46, 08021 Barcelona (entre Aribau y Muntaner)', 'Dentro de El Patrón a las 19:30h', 'image/d', 1);
INSERT INTO activities (title, activity_date, start_time, end_time, description, place_activity, meeting_point, image_event, account_id)VALUES('Pica-pica', '2018-09-09', '15:30', '17:00', '¿Te gustaría tomar una cerveza y que el pica-pica fuese gratis? Pues solo tienes que venir este jueves 6 de septiembre a El Patrón de Barcelona y podrás picotear entre risas y conocer gente guapa.', 'El Patrón. Travessera de Gràcia, 44-46, 08021 Barcelona (entre Aribau y Muntaner)', 'Dentro de El Patrón a las 19:30h', 'image/d', 1);
INSERT INTO activities (title, activity_date, start_time, end_time, description, place_activity, meeting_point, image_event, account_id)VALUES('Pica-pica', '2018-09-09', '15:30', '17:00', '¿Te gustaría tomar una cerveza y que el pica-pica fuese gratis? Pues solo tienes que venir este jueves 6 de septiembre a El Patrón de Barcelona y podrás picotear entre risas y conocer gente guapa.', 'El Patrón. Travessera de Gràcia, 44-46, 08021 Barcelona (entre Aribau y Muntaner)', 'Dentro de El Patrón a las 19:30h', 'image/d', 1);
INSERT INTO activities (title, activity_date, start_time, end_time, description, place_activity, meeting_point, image_event, account_id)VALUES('Pica-pica', '2018-09-09', '15:30', '17:00', '¿Te gustaría tomar una cerveza y que el pica-pica fuese gratis? Pues solo tienes que venir este jueves 6 de septiembre a El Patrón de Barcelona y podrás picotear entre risas y conocer gente guapa.', 'El Patrón. Travessera de Gràcia, 44-46, 08021 Barcelona (entre Aribau y Muntaner)', 'Dentro de El Patrón a las 19:30h', 'image/d', 1);
INSERT INTO activities (title, activity_date, start_time, end_time, description, place_activity, meeting_point, image_event, account_id)VALUES('Pica-pica', '2018-09-09', '15:30', '17:00', '¿Te gustaría tomar una cerveza y que el pica-pica fuese gratis? Pues solo tienes que venir este jueves 6 de septiembre a El Patrón de Barcelona y podrás picotear entre risas y conocer gente guapa.', 'El Patrón. Travessera de Gràcia, 44-46, 08021 Barcelona (entre Aribau y Muntaner)', 'Dentro de El Patrón a las 19:30h', 'image/d', 1);
INSERT INTO activities (title, activity_date, start_time, end_time, description, place_activity, meeting_point, image_event, account_id)VALUES('Pica-pica', '2018-09-09', '15:30', '17:00', '¿Te gustaría tomar una cerveza y que el pica-pica fuese gratis? Pues solo tienes que venir este jueves 6 de septiembre a El Patrón de Barcelona y podrás picotear entre risas y conocer gente guapa.', 'El Patrón. Travessera de Gràcia, 44-46, 08021 Barcelona (entre Aribau y Muntaner)', 'Dentro de El Patrón a las 19:30h', 'image/d', 1);
INSERT INTO activities (title, activity_date, start_time, end_time, description, place_activity, meeting_point, image_event, account_id)VALUES('Pica-pica', '2018-09-09', '15:30', '17:00', '¿Te gustaría tomar una cerveza y que el pica-pica fuese gratis? Pues solo tienes que venir este jueves 6 de septiembre a El Patrón de Barcelona y podrás picotear entre risas y conocer gente guapa.', 'El Patrón. Travessera de Gràcia, 44-46, 08021 Barcelona (entre Aribau y Muntaner)', 'Dentro de El Patrón a las 19:30h', 'image/d', 1);
INSERT INTO activities (title, activity_date, start_time, end_time, description, place_activity, meeting_point, image_event, account_id)VALUES('Pica-pica', '2018-09-09', '15:30', '17:00', '¿Te gustaría tomar una cerveza y que el pica-pica fuese gratis? Pues solo tienes que venir este jueves 6 de septiembre a El Patrón de Barcelona y podrás picotear entre risas y conocer gente guapa.', 'El Patrón. Travessera de Gràcia, 44-46, 08021 Barcelona (entre Aribau y Muntaner)', 'Dentro de El Patrón a las 19:30h', 'image/d', 1);
INSERT INTO activities (title, activity_date, start_time, end_time, description, place_activity, meeting_point, image_event, account_id)VALUES('Pica-pica', '2018-09-09', '15:30', '17:00', '¿Te gustaría tomar una cerveza y que el pica-pica fuese gratis? Pues solo tienes que venir este jueves 6 de septiembre a El Patrón de Barcelona y podrás picotear entre risas y conocer gente guapa.', 'El Patrón. Travessera de Gràcia, 44-46, 08021 Barcelona (entre Aribau y Muntaner)', 'Dentro de El Patrón a las 19:30h', 'image/d', 1);
INSERT INTO activities (title, activity_date, start_time, end_time, description, place_activity, meeting_point, image_event, account_id)VALUES('Pica-pica', '2018-09-09', '15:30', '17:00', '¿Te gustaría tomar una cerveza y que el pica-pica fuese gratis? Pues solo tienes que venir este jueves 6 de septiembre a El Patrón de Barcelona y podrás picotear entre risas y conocer gente guapa.', 'El Patrón. Travessera de Gràcia, 44-46, 08021 Barcelona (entre Aribau y Muntaner)', 'Dentro de El Patrón a las 19:30h', 'image/d', 1);
INSERT INTO activities (title, activity_date, start_time, end_time, description, place_activity, meeting_point, image_event, account_id)VALUES('Pica-pica', '2018-09-09', '15:30', '17:00', '¿Te gustaría tomar una cerveza y que el pica-pica fuese gratis? Pues solo tienes que venir este jueves 6 de septiembre a El Patrón de Barcelona y podrás picotear entre risas y conocer gente guapa.', 'El Patrón. Travessera de Gràcia, 44-46, 08021 Barcelona (entre Aribau y Muntaner)', 'Dentro de El Patrón a las 19:30h', 'image/d', 1);
INSERT INTO activities (title, activity_date, start_time, end_time, description, place_activity, meeting_point, image_event, account_id)VALUES('Pica-pica', '2018-09-09', '15:30', '17:00', '¿Te gustaría tomar una cerveza y que el pica-pica fuese gratis? Pues solo tienes que venir este jueves 6 de septiembre a El Patrón de Barcelona y podrás picotear entre risas y conocer gente guapa.', 'El Patrón. Travessera de Gràcia, 44-46, 08021 Barcelona (entre Aribau y Muntaner)', 'Dentro de El Patrón a las 19:30h', 'image/d', 1);
INSERT INTO activities (title, activity_date, start_time, end_time, description, place_activity, meeting_point, image_event, account_id)VALUES('Pica-pica', '2018-09-09', '15:30', '17:00', '¿Te gustaría tomar una cerveza y que el pica-pica fuese gratis? Pues solo tienes que venir este jueves 6 de septiembre a El Patrón de Barcelona y podrás picotear entre risas y conocer gente guapa.', 'El Patrón. Travessera de Gràcia, 44-46, 08021 Barcelona (entre Aribau y Muntaner)', 'Dentro de El Patrón a las 19:30h', 'image/d', 1);
INSERT INTO activities (title, activity_date, start_time, end_time, description, place_activity, meeting_point, image_event, account_id)VALUES('Pica-pica', '2018-09-09', '15:30', '17:00', '¿Te gustaría tomar una cerveza y que el pica-pica fuese gratis? Pues solo tienes que venir este jueves 6 de septiembre a El Patrón de Barcelona y podrás picotear entre risas y conocer gente guapa.', 'El Patrón. Travessera de Gràcia, 44-46, 08021 Barcelona (entre Aribau y Muntaner)', 'Dentro de El Patrón a las 19:30h', 'image/d', 1);
INSERT INTO activities (title, activity_date, start_time, end_time, description, place_activity, meeting_point, image_event, account_id)VALUES('Pica-pica', '2018-09-09', '15:30', '17:00', '¿Te gustaría tomar una cerveza y que el pica-pica fuese gratis? Pues solo tienes que venir este jueves 6 de septiembre a El Patrón de Barcelona y podrás picotear entre risas y conocer gente guapa.', 'El Patrón. Travessera de Gràcia, 44-46, 08021 Barcelona (entre Aribau y Muntaner)', 'Dentro de El Patrón a las 19:30h', 'image/d', 1);
INSERT INTO activities (title, activity_date, start_time, end_time, description, place_activity, meeting_point, image_event, account_id)VALUES('Pica-pica', '2018-09-09', '15:30', '17:00', '¿Te gustaría tomar una cerveza y que el pica-pica fuese gratis? Pues solo tienes que venir este jueves 6 de septiembre a El Patrón de Barcelona y podrás picotear entre risas y conocer gente guapa.', 'El Patrón. Travessera de Gràcia, 44-46, 08021 Barcelona (entre Aribau y Muntaner)', 'Dentro de El Patrón a las 19:30h', 'image/d', 1);
INSERT INTO activities (title, activity_date, start_time, end_time, description, place_activity, meeting_point, image_event, account_id)VALUES('Pica-pica', '2018-09-09', '15:30', '17:00', '¿Te gustaría tomar una cerveza y que el pica-pica fuese gratis? Pues solo tienes que venir este jueves 6 de septiembre a El Patrón de Barcelona y podrás picotear entre risas y conocer gente guapa.', 'El Patrón. Travessera de Gràcia, 44-46, 08021 Barcelona (entre Aribau y Muntaner)', 'Dentro de El Patrón a las 19:30h', 'image/d', 1);
INSERT INTO activities (title, activity_date, start_time, end_time, description, place_activity, meeting_point, image_event, account_id)VALUES('Pica-pica', '2018-09-09', '15:30', '17:00', '¿Te gustaría tomar una cerveza y que el pica-pica fuese gratis? Pues solo tienes que venir este jueves 6 de septiembre a El Patrón de Barcelona y podrás picotear entre risas y conocer gente guapa.', 'El Patrón. Travessera de Gràcia, 44-46, 08021 Barcelona (entre Aribau y Muntaner)', 'Dentro de El Patrón a las 19:30h', 'image/d', 1);
INSERT INTO activities (title, activity_date, start_time, end_time, description, place_activity, meeting_point, image_event, account_id)VALUES('Pica-pica', '2018-09-09', '15:30', '17:00', '¿Te gustaría tomar una cerveza y que el pica-pica fuese gratis? Pues solo tienes que venir este jueves 6 de septiembre a El Patrón de Barcelona y podrás picotear entre risas y conocer gente guapa.', 'El Patrón. Travessera de Gràcia, 44-46, 08021 Barcelona (entre Aribau y Muntaner)', 'Dentro de El Patrón a las 19:30h', 'image/d', 1);
INSERT INTO activities (title, activity_date, start_time, end_time, description, place_activity, meeting_point, image_event, account_id)VALUES('Pica-pica', '2018-09-09', '15:30', '17:00', '¿Te gustaría tomar una cerveza y que el pica-pica fuese gratis? Pues solo tienes que venir este jueves 6 de septiembre a El Patrón de Barcelona y podrás picotear entre risas y conocer gente guapa.', 'El Patrón. Travessera de Gràcia, 44-46, 08021 Barcelona (entre Aribau y Muntaner)', 'Dentro de El Patrón a las 19:30h', 'image/d', 1);
INSERT INTO activities (title, activity_date, start_time, end_time, description, place_activity, meeting_point, image_event, account_id)VALUES('Pica-pica', '2018-09-09', '15:30', '17:00', '¿Te gustaría tomar una cerveza y que el pica-pica fuese gratis? Pues solo tienes que venir este jueves 6 de septiembre a El Patrón de Barcelona y podrás picotear entre risas y conocer gente guapa.', 'El Patrón. Travessera de Gràcia, 44-46, 08021 Barcelona (entre Aribau y Muntaner)', 'Dentro de El Patrón a las 19:30h', 'image/d', 1);
INSERT INTO activities (title, activity_date, start_time, end_time, description, place_activity, meeting_point, image_event, account_id)VALUES('Pica-pica', '2018-09-09', '15:30', '17:00', '¿Te gustaría tomar una cerveza y que el pica-pica fuese gratis? Pues solo tienes que venir este jueves 6 de septiembre a El Patrón de Barcelona y podrás picotear entre risas y conocer gente guapa.', 'El Patrón. Travessera de Gràcia, 44-46, 08021 Barcelona (entre Aribau y Muntaner)', 'Dentro de El Patrón a las 19:30h', 'image/d', 1);
INSERT INTO activities (title, activity_date, start_time, end_time, description, place_activity, meeting_point, image_event, account_id)VALUES('Pica-pica', '2018-09-09', '15:30', '17:00', '¿Te gustaría tomar una cerveza y que el pica-pica fuese gratis? Pues solo tienes que venir este jueves 6 de septiembre a El Patrón de Barcelona y podrás picotear entre risas y conocer gente guapa.', 'El Patrón. Travessera de Gràcia, 44-46, 08021 Barcelona (entre Aribau y Muntaner)', 'Dentro de El Patrón a las 19:30h', 'image/d', 1);
INSERT INTO activities (title, activity_date, start_time, end_time, description, place_activity, meeting_point, image_event, account_id)VALUES('Pica-pica', '2018-09-09', '15:30', '17:00', '¿Te gustaría tomar una cerveza y que el pica-pica fuese gratis? Pues solo tienes que venir este jueves 6 de septiembre a El Patrón de Barcelona y podrás picotear entre risas y conocer gente guapa.', 'El Patrón. Travessera de Gràcia, 44-46, 08021 Barcelona (entre Aribau y Muntaner)', 'Dentro de El Patrón a las 19:30h', 'image/d', 1);
INSERT INTO activities (title, activity_date, start_time, end_time, description, place_activity, meeting_point, image_event, account_id)VALUES('Pica-pica', '2018-09-09', '15:30', '17:00', '¿Te gustaría tomar una cerveza y que el pica-pica fuese gratis? Pues solo tienes que venir este jueves 6 de septiembre a El Patrón de Barcelona y podrás picotear entre risas y conocer gente guapa.', 'El Patrón. Travessera de Gràcia, 44-46, 08021 Barcelona (entre Aribau y Muntaner)', 'Dentro de El Patrón a las 19:30h', 'image/d', 1);
INSERT INTO activities (title, activity_date, start_time, end_time, description, place_activity, meeting_point, image_event, account_id)VALUES('Pica-pica', '2018-09-09', '15:30', '17:00', '¿Te gustaría tomar una cerveza y que el pica-pica fuese gratis? Pues solo tienes que venir este jueves 6 de septiembre a El Patrón de Barcelona y podrás picotear entre risas y conocer gente guapa.', 'El Patrón. Travessera de Gràcia, 44-46, 08021 Barcelona (entre Aribau y Muntaner)', 'Dentro de El Patrón a las 19:30h', 'image/d', 1);
INSERT INTO activities (title, activity_date, start_time, end_time, description, place_activity, meeting_point, image_event, account_id)VALUES('Pica-pica', '2018-09-09', '15:30', '17:00', '¿Te gustaría tomar una cerveza y que el pica-pica fuese gratis? Pues solo tienes que venir este jueves 6 de septiembre a El Patrón de Barcelona y podrás picotear entre risas y conocer gente guapa.', 'El Patrón. Travessera de Gràcia, 44-46, 08021 Barcelona (entre Aribau y Muntaner)', 'Dentro de El Patrón a las 19:30h', 'image/d', 1);
INSERT INTO activities (title, activity_date, start_time, end_time, description, place_activity, meeting_point, image_event, account_id)VALUES('Pica-pica', '2018-09-09', '15:30', '17:00', '¿Te gustaría tomar una cerveza y que el pica-pica fuese gratis? Pues solo tienes que venir este jueves 6 de septiembre a El Patrón de Barcelona y podrás picotear entre risas y conocer gente guapa.', 'El Patrón. Travessera de Gràcia, 44-46, 08021 Barcelona (entre Aribau y Muntaner)', 'Dentro de El Patrón a las 19:30h', 'image/d', 1);
INSERT INTO activities (title, activity_date, start_time, end_time, description, place_activity, meeting_point, image_event, account_id)VALUES('Pica-pica', '2018-09-09', '15:30', '17:00', '¿Te gustaría tomar una cerveza y que el pica-pica fuese gratis? Pues solo tienes que venir este jueves 6 de septiembre a El Patrón de Barcelona y podrás picotear entre risas y conocer gente guapa.', 'El Patrón. Travessera de Gràcia, 44-46, 08021 Barcelona (entre Aribau y Muntaner)', 'Dentro de El Patrón a las 19:30h', 'image/d', 1);